version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=fitsync
      - POSTGRES_PASSWORD=fitsync
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: soeren.oehding@gmail.com
      PGADMIN_DEFAULT_PASSWORD: passwort
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  db:
    driver: local
  pgadmin:
    driver: local
